apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-pod
  labels:
    app.kubernetes.io/app: grade-submission
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: grade-submission-portal
spec:
  containers:
  - name: grade-submission-portal
    image: rslim087/kubernetes-course-grade-submission-portal:latest
    env:
      - name: GRADE_SERVICE_HOST
        value: grade-submission-api-service
    resources:
      limits:
        memory: 500Mi
      requests:
        cpu: 200m
        memory: 500Mi
    ports:
      - containerPort: 5001